config/routes.rb
Lauralee::Application.routes.draw do

  # Home Page
  root to: "welcome#index"

  # Main Nav / Works
  get 'work/majorfinder' => 'work#majorfinder'
  get 'work/discovery' => 'work#discovery'
  get 'work/bloccit' => 'work#bloccit', path: "work/training-community"
  get 'work/wikiland' => 'work#wikiland'

  # Main Nav / About
  get "/about" => 'welcome#about'
  get "/test" => 'welcome#test'
  get "/varsitytutors" => 'welcome#varsitytutors'
  get "/confirmed" => 'welcome#confirm_subscription'

  # Playground
  get "/playground/*page" => "playground#show"
  get "/playground" => "playground#show", page: "index"

  # Main Nav / Feedback
  resources :feedbacks

  # Main Nav / Lessons
  get '/git', to: redirect('/courses')
  get '/git/lessons', to: redirect('/courses')
  resources :courses do
    resources :lessons, path: "lesson"
  end
  get '/git' => 'courses#git'


  # Devise
  devise_for :users
  resources :users, only: [:update]

  # Resources -> remove soon
  scope '/resources' do
    get '/freeimages' => 'welcome#freeimages'
    get "/about_me" => 'welcome#about_me', path: "a-little-about-me"
  end
  get "/resources" => 'welcome#resources'

  # Blog
  get 'blog/tags' => 'tags#index', as: :tags
  get 'blog/tags/:tag' => 'tags#show', as: :tag
  resources :posts, path: "blog"



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @post = Post.order("created_at DESC").limit(5)
  end

  def resources
  	@feedback = Feedback.new
  end

  def freeimages

  end

  def about_me
  end

  def about
  end

  def test
  end

  def varsitytutors
  end

	def confirm_subscription
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_sign_in.html.erb
<!-- Sign In Modal
=================================== -->
<div id="sign-in-modal", class="reveal-modal" data-reveal >
	<% if user_signed_in? %>
		<h2 class="text-center">Welcome!</h2>
		<p>Information will be coming soon.</p>
	<% else %>
		<div class="small-spacer">
			<h2 class="text-center">Sign In</h2>
		</div>
		
	  <!-- <p>Reveal makes these very easy to summon and dismiss. The close button is simply an anchor with a unicode character icon and a class of <code>close-reveal-modal</code>. Clicking anywhere outside the modal will also dismiss it.</p>
	  <p>Finally, if your modal summons another Reveal modal, the plugin will handle that for you gracefully.</p> -->
	  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
	  	<div id="form">
	  		<!-- Sign In Form -->
	  		<div class="row">
		  		<div class="small-12 medium-8 medium-centered columns">
		  			<!-- Email -->
					  <%= f.email_field :email, autofocus: true, placeholder: "Email", class: "border-bottom" %>

					  <!-- Password -->
					  <%= f.password_field :password, autocomplete: "off", placeholder: "Password", class: "border-bottom" %>

					  <!-- Remember Me -->
					  <% if devise_mapping.rememberable? -%>
					    <%= f.check_box :remember_me %> <%= f.label :remember_me %>
					  <% end -%>

					  <!-- Sign Up Button -->
					  <%= f.submit "Sign in", class: "button expand" %>
		  		</div>
		  	</div>

		  	<!-- Link to Sign Up Modal -->
			  <div class="medium-spacer-top">
			  	<div class="row">
			  		<div class="small-10 medium-4 small-centered medium-centered columns">
			  			<p><a href="#" data-reveal-id="sign-up-modal" class="secondary button expand">Sign Up</a></p>
			  		</div>
			  	</div>
			  </div>


	  	</div>
		<% end %>
	<% end %>
  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/welcome/_sign_up.html.erb
<!-- Sign Up Modal
============================== -->
<div id="sign-up-modal", class="reveal-modal" data-reveal >
	<% if user_signed_in? %>
		<h2 class="text-center">Congratulations, you've already signed up!</h2>
		<% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
			<p>We're waiting for you to confirm your account.  Please check your email and click on the link.</p>
		<% else %>
			<p>You've confirmed your account and are signed up. <%= link_to "Tell me what you want to learn", new_feedback_path, class: "pink-link-center" %> or let me <%= link_to "thank you for signing up", resources_path, class: "pink-link-center" %>.</p>
		<% end %>
		<!-- if they haven't confirmed their account.. link to resend confirmation instructions else go to coming soon page. -->
	<% else %>
		<div class="small-spacer">
			<h2 class="text-center">Sign Up For Free</h2>
		</div>
		<div id="form">
			<div class="row">
				<div class="small-12 medium-8 medium-centered columns">
					<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
						<%= devise_error_messages! %>

						<%= f.text_field :name, autofocus: true, placeholder: "First Name", class: "border-bottom" %>

						<%= f.email_field :email, autofocus: true, placeholder: "Email", class: "border-bottom" %>

						<%= f.password_field :password, autocomplete: "off", placeholder: "Password", class: "border-bottom" %>

						<%= f.submit "Send Me Training When It's Available", class: "button expand sign-up" %>
					<% end %>
				</div>
			</div>

		<!-- Link to Sign Up Modal -->
	  <div class="medium-spacer-top">
	  	<div class="row">
	  		<div class="small-10 medium-4 small-centered medium-centered columns">
	  			<p><a href="#" data-reveal-id="sign-in-modal" class="secondary button expand">Sign In</a></p>
	  		</div>
	  	</div>
	  </div>
	<% end %>
  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/welcome/about.html.erb
<div id="about">

	<!-- Bio -->
	<div class="row big-spacer-top">
		<div class="small-12 columns">
			<div class="small-spacer-bottom">
				<%= image_tag "my-family-2.jpg" %>
			</div>
		</div>
	</div>
	<div class="row small-spacer-top medium-spacer-bottom">
		<div class="small-10 small-centered columns">
			<p>
				I began working on websites in 2006. However when I began I never would have imagined the path my professional life would take.
			</p>
			<p>
				I started out in web usability (I have a masters degree in applied psychology with an emphasis in human-computer interaction). What this means is that I understand the psychology behind how to make a website users love. I did usability, I trained others how to do usability (one-on-one, seminars, and I developed and taught University courses on the topic), and I ran a usability team.
			</p>
			<p>
				I never considered myself a creative person, whatever that means. If I could go back in time I'd tell young me that the reason I’m not creative is that I never really tried to be creative.
			</p>
			<p>
				The first time I tried to express my creativity was with small web design projects. I had hired someone to do a website for me and the design wasn’t as good as I wanted it to be. So I would design little parts of the interface. This went on for some time, the company I hired would deliver web designs and I would see flaws in the design (my usability training definitely played a role in this) and so I would redesign it and send it to them to create.
			</p>
			<p>
				Since I had self-identified as a non-creative person, it took me a long time to realize that my designs were not only better than this professional design company I had hired, but they were simply good without needing any comparison at all.
			</p>
			<p>
				Equipped with a new self title of maybe a creative person. Maybe. I designed a website and then I learned HTML and CSS and built it. It was so simple and probably not very good but I loved every second of it. Creating it brought me alive.
			</p>
			<p>
				I knew I had to do more websites. So, I did. I designed and built multiple websites. Some for myself and some for others. Before going very far down this path I realized I needed to learn more than just HTML and CSS. I started learning a couple different programming languages (PHP and Python for you nerds out there) but when I started learning Ruby on Rails I knew it had ruined me for all the other languages. I loved it. I found it beautiful and clean.
			</p>
			<p>
				Looking back I realize that with each project I could see myself getting better. My goal is for that to never change. Ever.
			</p>
			<p>
				I am the web designer at <%= link_to "KickoffLabs", "http://www.kickofflabs.com", class: "clean-link" %>. When I'm not working at KickoffLabs, you might find me spending time with my family, reading (I am a voracious reader), or working on one of my side projects. Right now I'm creating <%= link_to "memorates", "http://www.memorates.com", class: "clean-link" %>.
			</p>
			<p>
				I absolutely love what I do.
			</p>

		</div>

	</div>


</div>

app/views/welcome/about_me.html.erb
<div class="row">
	<div class="big-spacer-top">
		<h2>A Little About Me and Why I Decided to Start This Training Series</h2>
	</div>
</div>

<div class="row">
	<%= image_tag "a-little-about-me.jpg" %>
</div>

<div class="row">
	<div class="small-spacer-top medium-spacer-bottom">
		<p>Imagine with me for a second.  You have created a website.  Or maybe you’ve hired someone to create a website for you.  You put your heart and soul into making it the best it could possibly be.  Now it is live, it is “done”, and it is <em>not</em> what you envisioned. Not completely.  Maybe not even at all.  In fact, you realize that even though your website is “done” there’s a lot of other things you see you would like to change or fix or improve. </p>

		<p>Maybe you haven’t had an experience like this.  I hope you haven’t.  But, I have.  Actually, I have quite a few like this.  In 2008 I hired a company and paid them almost $20,000 to create a website for me.  Granted it was complex and the programming involved wasn’t simple.  At least that’s what I thought back in 2008.  Now that I know how to program I realize it really wasn’t that hard.  But, that’s beside the point.  The point is, I paid quite a bit of money for a website that at the end of the day was terrible.  I couldn’t even use it.  I had to scrap it and start all over.  I had put my heart and soul and hard earned money into making it the best it could be.  And I failed.  I was crushed.</p>

		<p>So, who’s fault was it?  For a while I thought it was the company I hired.  I guess it was just easier or felt better to blame someone else.  But, since I’ve had some time to think about it I realize that although they had a role in this failure.  I was ultimately the reason it failed.</p>

		<p>This might not have been so bad if this was the only experience trying to make an amazing website but failing.  It’s still painful for me to acknowledge that a year later I improved in some ways but made a lot of the same mistakes again.  I hired another company.  I paid them a lot of money.  I made something better but still not good enough.  Something that still wasn’t what I envisioned.</p>

		<p>I wish I could say that these two experiences have taught me what I needed to know to make great websites.  But, they didn’t.  I made a lot of the same mistakes over and over.  I am sure I am still making some of those same mistakes I made back in 2008.  But, I can tell you with certainty that I’m not making very many of them any more.  I’ve learned a lot.</p>

		<p><em><strong>One of the best things I did was to keep making mistakes.</strong></em> I didn’t give up.  And because I didn’t I have gotten better.  A lot better.</p>

		<p><em><strong>The second best thing I did was to learn to make websites on my own.</strong></em> This allowed me to continue to make mistakes but those mistakes weren’t going to cost me tens of thousands of dollars.  And what I found was that my mistakes became less and less with each week that passed and especially with each project.</p>

		<p><em><strong>I didn’t allow fear to stop me.</strong></em>  I was afraid to fail.  But I didn’t let that fear stop me.  In the process I learned and embraced a beautiful truth.</p> 

		<blockquote>Taking action, despite the fear and vulnerability you may feel, will expand your limits and multiply your opportunities</blockquote>  

		<p>No one is good at anything the first time they do it. You just have to do it and don’t let fear stop you.</p>

		<p>I still don’t know everything about making incredible websites.  But, I know a whole lot more than I did in 2008.  And the more clients I have and the more projects I begin I realize I know quite a bit about websites and how to make them <em>incredible</em>.  I’m not talking about just making a <em>nice</em> website - a lot of people can do that.  I’m not talking about average.  I’m talking about <em>remarkable</em>.  I’m talking about how to make your website a <%= link_to "purple cow", "http://www.sethgodin.com/purple/", class: "pink-link-center" %>, as Seth Godin would say. </p>

		<p>I want you to avoid the huge mistakes I’ve made.  Sure, you might stumble and make your own mistakes.  And that’s good if you learn from them. But, most importantly I want to see you succeed.  I’m going to do all I can to see that you do. </p>

		<p>That’s the whole purpose of this blog or collection of resources or whatever you want to call it.  That’s why I’m going to post something every week that I wish the 2008 version of myself had known.  Something I know you will need to know in order to make incredible websites.  I would love <%= link_to "your help", new_feedback_path, class: 'pink-link-center' %>.  It should only take you one minute. </p>

		<p>If you and I met up and you could ask me anything about making incredible websites.  What would you want to know?  <%= link_to "What would you want me to show you?", new_feedback_path, class: "pink-link-center" %></p>

		<p>Thank you so much for any feedback you can offer at any point!  I will openly and honestly listen to everything that is suggested.  Thank you so much for taking a minute out of your day to tell me what you want to learn.</p>

		<p>In the next post we’ll cover what is probably <em>the single most important</em> thing about making incredible websites.</p>

	</div>
</div>

app/views/welcome/comingsoon.html.erb
<div id="comingsoon-intro">
	<div class="row">
		<h1 class="text-center upper">Thank you</h1>
		<h1 class="text-center">for taking this journey with me!</h1>
	</div>
</div>

<!-- <div class="blog">
	<div class="row">
		<div class="big-spacer-top medium-spacer-bottom">
			<h2><%= link_to "A Little About Me and Why I Decided to Start This Training Series", about_me_path %></h2>
			<div class="small-12 columns small-spacer-bottom">
				<p>I've been thinking about creating these resources for some time now.  In this post I explain a little bit my early failures and what they taught me.  Ultimately, this is what I am going to do my best to help you avoid.</p>
			</div>
			<div class="small-12 medium-8 medium-centered columns">
				<%= link_to "View Article", about_me_path, class: 'button expand' %>
			</div>
		</div>
	</div>
</div> -->

<div id="freebie">
	<div class="row">
		<div class="big-spacer">
			<h2><%= link_to "Something That Every Web Project Needs", freeimages_path %></h2>
			<h3>Here's one of many resources I'll be giving you: high-quality images and icons.</h3>
			<%= link_to image_tag("images-thanks.png"), freeimages_path %>
			<p>I've literally spent $1,000's of dollars on images because I didn't know where to find <em>beautiful, high-quality, FREE images</em>.  I'll share the ones I've collected and how to find them yourself.</p>
			<p>This is my way of saying thank you for signing up on lauraleeflores.com.  I sincerely hope this is an extremely valuable resource for you on your journey to making remarkable websites.</p>
			<div class="small-12 medium-8 medium-centered columns">
				<%= link_to "Gimme Free Images!", freeimages_path, class: "button expand button-pink" %>
				<!-- Later make this button read "Add This Resource to My Account" -->
			</div>
		</div>
	</div>
</div>

<div id="user-input">
	<div class="row">
		<div class="big-spacer">
			<h2>I Have a Request...</h2>
			<p>I'm working hard creating resources and training that <em>I think</em> you'll love. But, I'm honestly not sure if I'm focusing on what you <em>most want to learn</em>.</p>
			<p>Let's say we were sitting together at the computer for the next 15 minutes.  And you could ask me anything about websites, what would you want to me to show you?  What is the first thing you would want to learn about?</p>
			<%= render 'feedbacks/form' %>
		</div>
	</div>
</div>

app/views/welcome/confirm_subscription.html.slim
.row
  .small-9.big-spacer-top.centered style="margin-left:auto;margin-right:auto;"
    h1 style="font-weight:200;font-size:3rem;line-height:1;margin-bottom:1.5rem;margin-top:2rem;" Thank you for confirming your email.
    p You are awesome! Be on the lookout for an email from me very soon. In the meantime if you have any questions you can email me any time at lauralee@lauraleeflores.com.

app/views/welcome/freeimages.html.slim
.row
	.big-spacer-top.text-center
		h1.small-spacer-top Free - No Restrictions - Images
		p Make your designs better than average for free and without restrictions.

.row.small-spacer
	.free-image-wrapper
		.small-4.columns
			= link_to "http://unsplash.com/", target: :_blank do
				= image_tag("free_images/unsplash.jpg")
				h3 Unsplash
	.free-image-wrapper
		.small-4.columns
			= link_to "https://stocksnap.io/", target: :_blank do
				= image_tag("free_images/stocksnap.jpg")
				h3 StockSnap
	.free-image-wrapper
		.small-4.columns
			= link_to "https://www.pexels.com/", target: :_blank do
				= image_tag("free_images/pexel.jpg")
				h3 Pexels

.row.small-spacer
	.free-image-wrapper
		.small-4.columns
			= link_to "http://picjumbo.com/", target: :_blank do
				= image_tag("free_images/picjumbo.jpg")
				h3 PicJumbo
	.free-image-wrapper
		.small-4.columns
			= link_to "http://www.gratisography.com/", target: :_blank do
				= image_tag("free_images/gratisography.jpg")
				h3 Gratisography
	.free-image-wrapper
		.small-4.columns
			= link_to "http://deathtothestockphoto.com/", target: :_blank do
				= image_tag("free_images/deathtostock.jpg")
				h3 Death to Stock
.row.small-spacer
	.free-image-wrapper
		.small-4.columns
			= link_to "http://foodiesfeed.com/download/", target: :_blank do
				= image_tag("free_images/foodies.jpg")
				h3 Foodie's Feed
	.free-image-wrapper
		.small-4.columns
			= link_to "http://jaymantri.com/", target: :_blank do
				= image_tag("free_images/jaymantri.jpg")
				h3 Jay Mantri
	.free-image-wrapper
		.small-4.columns
			= link_to "http://picography.co/", target: :_blank do
				= image_tag("free_images/picography.jpg")
				h3 Picography
.row.small-spacer
	.free-image-wrapper
		.small-4.columns
			= link_to "http://magdeleine.co/", target: :_blank do
				= image_tag("free_images/magdeleine.jpg")
				h3 Magdeleine.co
	.free-image-wrapper
		.small-4.columns
			= link_to "http://pixabay.com/", target: :_blank do
				= image_tag("free_images/pixabay.jpg")
				h3 Pixabay
	.free-image-wrapper
		.small-4.columns
			= link_to "http://www.morguefile.com/archive", target: :_blank do
				= image_tag("free_images/morguefile.jpg")
				h3 MorgueFile
.row.small-spacer
	.free-image-wrapper
		.small-4.columns
			= link_to	"http://thestocks.im/", target: :_blank do
				= image_tag("free_images/the-stock.jpg")
				h3 The Stocks
	.free-image-wrapper
		.small-4.columns
			= link_to	"http://nos.twnsnd.co/", target: :_blank do
				= image_tag("free_images/newtownsend.jpg")
				h3 New Old Stock
	.free-image-wrapper
		.small-4.columns
			= link_to	"http://publicdomainarchive.com/", target: :_blank do
				= image_tag("free_images/publicdomainarchive.jpg")
				h3 Public Domain Archive
.row.small-spacer
	.free-image-wrapper
		.small-4.columns
			= link_to "http://www.publicdomainpictures.net/", target: :_blank do
				= image_tag("free_images/publicdomain.jpg")
				h3 Public Domain Pictures
	.free-image-wrapper
		.small-4.columns
			= link_to "https://www.flickr.com/commons/", target: :_blank do
				= image_tag("free_images/flickrcommons.jpg")
				h3 The Commons on Flickr
	.free-image-wrapper
		.small-4.columns
			= link_to "http://freerangestock.com/popular_photos.php", target: :_blank do
				= image_tag("free_images/freerange.jpg")
				h3 FreeRange



.row
	.big-spacer-top.text-center
		h1.small-spacer-top Other Free Resources
		p In addition to images, you may be in need of icons, videos, and other resources. Those will be included in this section.

.row.small-spacer
	.free-image-wrapper
		.small-4.columns
			= link_to "https://coverr.co/", target: :_blank do
				= image_tag("free_images/coverr.jpg")
				h3 Coverr

	.free-image-wrapper
		.small-4.columns
			= link_to "http://mazwai.com/", target: :_blank do
				= image_tag("free_images/mazwai.jpg")
				h3 Stock Videos
	.free-image-wrapper
		.small-4.columns
			= link_to "http://mariodelvalle.github.io/CaptainIconWeb/index.html", target: :_blank do
				= image_tag("free_images/captainicon.jpg")
				h3 Captain Icon

app/views/welcome/index.html.erb
<div id="home-page">
	<p>
		Hi, I am Lauralee. I’m a web designer, ruby on rails developer, and usability expert. <%= link_to "Learn a little more about me", about_path, class: "clean-link" %>. Or <%= link_to "see what I have to say", posts_path, class: "clean-link" %>.
	</p>
</div>

app/views/welcome/resources.html.erb
<div id="resources-landing">

	<!-- Header -->
	<section class="intro">

		<!-- Heading -->
		<div class="row text-center">
			<div class="small-12 columns big-spacer-top mini-spacer-bottom">
				<h1>Resources &amp; Training</h1>
			</div>
		</div>

		<!-- Tagline -->
		<div class="row text-center">
			<div class="small-12 medium-8 small-centered columns medium-spacer-bottom">
				<h2>I’m beginning to create resources that will allow you to create incredible websites.</h2>
			</div>
		</div>

	</section>

	<!-- Free Stuff -->
	<section class="offers">
		<div class="row" data-equalizer>

			<!-- Free Images -->
			<div class="small-12 large-6 columns card" data-equalizer-watch>
				<div class="image-container">
					<%= image_tag "web-page-illustration.png" %>
				</div>
				<div class="content-container">
					<h4>Free Images</h4>
					<p>I've literally spent $1,000's of dollars on images because I didn't know where to find beautiful, high-quality, FREE images. I'll share the ones I've collected and how to find them yourself.</p>
					<p><%= link_to "Gimme Free Images", freeimages_path, class: "button expand" %></p>
				</div>
			</div>

			<!-- Free Rails Course -->
			<div class="small-12 large-6 columns card" data-equalizer-watch>
				<div class="image-container">
					<%= image_tag "web-app-illustration.png" %>
				</div>
				<div class="content-container">
					<h4>Learn Rails</h4>
					<p>Ruby on Rails is the fastest growing web development language and rails programers are the best paid with the highest demand. Why? Because you create and iterate on your application fast, really fast. </p>
					<% if current_user %>
						<p class="signed-up">Because your're signed up I will email you when the course is ready.</p>
					<% else %>
						<p><%= link_to "Notify Me When Course Is Ready", new_user_registration_path, class: "button expand" %></p>
					<% end %>
				</div>
			</div>
		</div>
	</section>
</div>

<div id="user-input">
	<div class="row">
		<div class="big-spacer">
			<h2>I Have a Request...</h2>
			<p>I'm working hard creating resources and training that <em>I think</em> you'll love. But, I'm honestly not sure if I'm focusing on what you <em>most want to learn</em>.</p>
			<p>If I were to create a course or a valuable resource <em>just for you</em>, what would it be? What do you want to learn from me?</p>
			<%= render 'feedbacks/form' %>
		</div>
	</div>
</div>

app/views/welcome/test.html.erb
<style>
#nav {
	display: none;
}
style[class="editme" i] {
	display: block;
	width: 80%;
	margin: 1rem auto;
	padding: 10px;
	border: 1px solid gray;
	font-family: "Courier New", Courier, monospace;
	background: whitesmoke;
	line-height: 1.5;
}
</style>
<style contenteditable class="editme">
p {
	color: red;
}
body {
	background: blue;
}
</style>
<div class="big-spacer-top">
	<p>Testing</p>
</div>
<div class="big-spacer-top">
	<div class="grid">
		<div class="browser">
			<span class="circle"></span>
			<span class="circle"></span>
			<span class="circle"></span>
		</div>

		<header class="logo">
			<div class="logo">
			</div>
		</header>

		<header class="nav">
			<div class="links">
			</div>
			<div class="account">
			</div>
		</header>

		<aside class="left-nav">
			<ul>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
			</ul>
		</aside>

		<div class="body">
			<article class="card 1">
				<div class="text full">
				</div>
				<div class="text half">
				</div>
			</article>
			<article class="card 2">
				<div class="text full">
				</div>
				<div class="text half">
				</div>
			</article>
			<article class="card 3">
				<div class="text full">
				</div>
				<div class="text half">
				</div>
			</article>
			<article class="card 4">
				<div class="text full">
				</div>
				<div class="text half">
				</div>
			</article>
			<article class="card 5">
				<div class="text full">
				</div>
				<div class="text half">
				</div>
			</article>
			<article class="card 6">
				<div class="text full">
				</div>
				<div class="text half">
				</div>
			</article>
		</div>
	</div>
</div>

app/views/welcome/varsitytutors.html.erb
<div class="row">
	<div class="small-12 columns">
		
	</div>
</div>