config/routes.rb
Lauralee::Application.routes.draw do

  # Home Page
  root to: "welcome#index"

  # Main Nav / Works
  get 'work/majorfinder' => 'work#majorfinder'
  get 'work/discovery' => 'work#discovery'
  get 'work/bloccit' => 'work#bloccit', path: "work/training-community"
  get 'work/wikiland' => 'work#wikiland'

  # Main Nav / About
  get "/about" => 'welcome#about'
  get "/test" => 'welcome#test'
  get "/varsitytutors" => 'welcome#varsitytutors'
  get "/confirmed" => 'welcome#confirm_subscription'

  # Playground
  get "/playground/*page" => "playground#show"
  get "/playground" => "playground#show", page: "index"

  # Main Nav / Feedback
  resources :feedbacks

  # Main Nav / Lessons
  get '/git', to: redirect('/courses')
  get '/git/lessons', to: redirect('/courses')
  resources :courses do
    resources :lessons, path: "lesson"
  end
  get '/git' => 'courses#git'


  # Devise
  devise_for :users
  resources :users, only: [:update]

  # Resources -> remove soon
  scope '/resources' do
    get '/freeimages' => 'welcome#freeimages'
    get "/about_me" => 'welcome#about_me', path: "a-little-about-me"
  end
  get "/resources" => 'welcome#resources'

  # Blog
  get 'blog/tags' => 'tags#index', as: :tags
  get 'blog/tags/:tag' => 'tags#show', as: :tag
  resources :posts, path: "blog"



end

app/controllers/work_controller.rb
class WorkController < ApplicationController
	def majorfinder
	end

	def discovery
	end

	def bloccit
	end

	def wikiland
	end
end

app/helpers/work_helper.rb
module WorkHelper
end

app/views/work/bloccit.html.erb
<div class="blue-background">
	<div class="row text-center big-spacer-top">
		<h1 class="animated fadeInDown">Training Community</h1>
		<p class="no-tagline animated fadeIn">Learn web development. Suggest training material. Connect with other developers.</p>
	</div>
</div>

<div class="row big-spacer-top">
	<div class="small-12 medium-6 medium-centered columns" id="built-using">
		<ul>
			<li>Built Using</li>
			<li>Ruby & Ruby on Rails</li>
			<li>HTML / CSS / Javascript / AJAX</li>
			<li>SASS</li>
			<li>Heroku</li>
			<li>Postgresql</li>
			<li>Minimal Design</li>
		</ul>
	</div>
</div>

<div class="background-gray small-spacer-top">
	<div class="row">
		<div class="small-12 columns big-spacer">
			<%= link_to image_tag('work/bloccit-home.png'), "http://lauralee-bloccit.herokuapp.com/" %>
		</div>
	</div>
</div>
<div class="row medium-spacer">
	<div class="small-12 columns">
		<h3>Nested Routing</h3>
		<%= image_tag 'work/bloccit-nested-resources.jpg' %>
	</div>
</div>

<div class="row medium-spacer">
	<div class="small-12 columns">
		<h3>Posts in Markdown</h3>
		<div class="small-12 medium-10 medium-centered columns">
			<%= image_tag 'work/bloccit-markdown.gif' %>
		</div>
	</div>
</div>

<div class="row medium-spacer">
	<div class="small-12 columns">
		<h3>Add Avatar Image and Images to Posts</h3>
		<%= image_tag 'work/bloccit-images.jpg' %>
	</div>
</div>

<div class="row medium-spacer">
	<div class="small-12 columns">
		<h3>AJAX Commenting on Posts</h3>
		<%= image_tag 'work/bloccit-ajax.jpg' %>
	</div>
</div>

<div class="row medium-spacer">
	<div class="small-12 columns">
		<h3>Voting</h3>
		<%= image_tag 'work/bloccit-vote.jpg' %>
	</div>
</div>

<div class="row medium-spacer">
	<div class="small-12 columns">
		<h3>Favorite a Post</h3>
		<%= image_tag 'work/bloccit-favorite.jpg' %>
	</div>
</div>


<div class="row">
	<div class="small-12 medium-6 medium-centered columns big-spacer-bottom">
		<%= link_to "Visit the Training Community", "http://lauralee-bloccit.herokuapp.com/", class: "button expand", id: "ghost-button" %>
	</div>
</div>

<div class="background-gray big-spacer-top" id="work-show">
	<div class="row">
		<h4 class="text-center">See Some of My Other Projects</h4>
	</div>

	<!-- Major Finder and Discovery -->
	<div class="row big-spacer-bottom">
		<div class="small-spacer-top ">
			<div class="small-12 medium-6 columns portfolio">
				<%= link_to image_tag('work/majorfinder.jpg'), work_majorfinder_path, class: "border" %>
				<h3><%= link_to "Major Finder", work_majorfinder_path %></h3>
			</div>
			<div class="small-12 medium-6 columns portfolio">
				<%= link_to image_tag('work/wikiland.jpg'), work_wikiland_path, class: "border" %>
				<h3><%= link_to "WikiLand", "#" %></h3>
			</div>
		</div>
	</div>
</div>

app/views/work/discovery.html.erb
<div class="blue-background">
	<div class="row text-center big-spacer-top">
		<h1 class="animated fadeInDown">Discovery</h1>
		<p class="no-tagline animated fadeIn">Rails Engine. Personality Test.</p>
	</div>
</div>

<div class="row big-spacer-top">
	<div class="small-12 columns">
		<p>I built this engine with the intention of plugging it into <%= link_to "major finder", "http://majorfinder.com/", class: "pink-link-center" %>.  Many people who sign up don't have any idea what they would like to do for a major or career.  This personality test is a way for them to find some ideas based on their personality.</p>

	</div>
</div>

<div class="row big-spacer-bottom">
	<div class="small-12 medium-6 medium-centered columns" id="built-using">
		<ul>
			<li>Built Using</li>
			<li>Ruby & Ruby on Rails</li>
			<li>HTML</li>
			<li>Heroku</li>
			<li>Postgresql</li>
			<li>Minimal Design [IN PROCESS]</li>
			<li>CSS / SASS / Javascript / Angular JS [IN PROCESS]</li>
		</ul>
	</div>
</div>

<div class="row">
	<div class="small-12 medium-6 medium-centered columns big-spacer-bottom">
		<%= link_to "Visit Discovery on Github", "https://github.com/flores8/discovery", class: "button expand", id: "ghost-button" %>
	</div>
</div>

<div class="background-gray big-spacer-top" id="work-show">
	<div class="row">
		<h4 class="text-center">See Some of My Other Projects</h4>
	</div>

	<!-- Major Finder and Discovery -->
	<div class="row big-spacer-bottom">
		<div class="small-spacer-top ">
			<div class="small-12 medium-6 columns portfolio">
				<%= link_to image_tag('work/majorfinder.jpg'), work_majorfinder_path, class: "border" %>
				<h3><%= link_to "Major Finder", work_majorfinder_path %></h3>
			</div>
			<div class="small-12 medium-6 columns portfolio">
				<%= link_to image_tag('work/bloccit.jpg'), work_bloccit_path, class: "border" %>
				<h3><%= link_to "Training Community", work_bloccit_path %></h3>
			</div>
		</div>
	</div>
</div>

app/views/work/majorfinder.html.erb
<div class="blue-background">
	<div class="row text-center big-spacer-top">
		<h1 class="animated fadeInDown">Major Finder</h1>
		<p class="tagline animated fadeIn">Helping you make the most important decision of your life.</p>
		<div class="small-12 columns centered">
			<%= link_to image_tag('work/majorfinder-laptop.png'), "http://majorfinder.com/" %>
		</div>
	</div>
</div>

<div class="row big-spacer-top">
	<div class="small-12 medium-6 medium-centered columns" id="built-using">
		<ul>
			<li>Built Using</li>
			<li>Ruby & Ruby on Rails</li>
			<li>HTML / CSS / Javascript / Coffeescript</li>
			<li>SASS</li>
			<li>Heroku</li>
			<li>Postgresql</li>
			<li>Web Usability (lots and lots of usability work)</li>
			<li>Minimal Design</li>
			<li>Web Analytics</li>
			<li>Web Optimization</li>
		</ul>
	</div>
</div>

<div class="background-gray small-spacer-top">
	<div class="row">
		<div class="small-12 columns big-spacer">
			<%= link_to image_tag('work/majorfinder-major.png'), "http://majorfinder.com/majors/music" %>
		</div>
	</div>
</div>

<div class="row">
	<div class="small-12 medium-6 medium-centered columns medium-spacer">
		<%= link_to "Visit MajorFinder", "http://majorfinder.com/", class: "button expand", id: "ghost-button" %>
	</div>
</div>

<div class="background-gray big-spacer-top" id="work-show">
	<div class="row">
		<h4 class="text-center">See Some of My Other Projects</h4>
	</div>

	<!-- Major Finder and Discovery -->
	<div class="row big-spacer-bottom">
		<div class="small-spacer-top ">
			<div class="small-12 medium-6 columns portfolio">
				<%= link_to image_tag('work/discovery.jpg'), work_discovery_path, class: "border" %>
				<h3><%= link_to "Discovery", work_discovery_path %></h3>
			</div>
			<div class="small-12 medium-6 columns portfolio">
				<%= link_to image_tag('work/bloccit.jpg'), work_bloccit_path, class: "border" %>
				<h3><%= link_to "Training Community", work_bloccit_path %></h3>
			</div>
		</div>
	</div>
</div>

app/views/work/wikiland.html.erb
<div class="purple-background">
	<div class="row text-center big-spacer-top">
		<h1 class="animated fadeInDown">WikiLand</h1>
		<p class="tagline animated fadeIn">Create plublic and private markdown-based wikis.</p>
		<div class="small-12 columns centered">
			<%= link_to image_tag('work/wiki.png'), "http://wikiland.herokuapp.com/" %>
		</div>
	</div>
</div>

<div class="row big-spacer-top">
	<div class="small-12 medium-6 medium-centered columns" id="built-using">
		<ul id="purple">
			<li>Built Using</li>
			<li>Ruby & Ruby on Rails</li>
			<li>HTML / CSS / Javascript</li>
			<li>SASS</li>
			<li>Heroku</li>
			<li>Postgresql</li>
			<li>Stripe Integration</li>
			<li>Friendly URL's</li>
		</ul>
	</div>
</div>

<div class="background-gray small-spacer-top">
	<div class="row">
		<div class="small-12 columns big-spacer">
			<%= image_tag 'work/wiki-creation.png' %>
		</div>
	</div>
</div>

<div class="row">
	<div class="small-12 medium-6 medium-centered columns big-spacer-bottom">
		<%= link_to "Visit WikiLand", "http://wikiland.herokuapp.com/", class: "button expand", id: "ghost-button-purple" %>
	</div>
</div>

<div class="background-gray big-spacer-top" id="work-show">
	<div class="row">
		<h4 class="text-center">See Some of My Other Projects</h4>
	</div>

	<!-- Major Finder and Discovery -->
	<div class="row big-spacer-bottom">
		<div class="small-spacer-top ">
			<div class="small-12 medium-6 columns portfolio">
				<%= link_to image_tag('work/majorfinder.jpg'), work_majorfinder_path, class: "border" %>
				<h3><%= link_to "Major Finder", work_majorfinder_path %></h3>
			</div>
			<div class="small-12 medium-6 columns portfolio">
				<%= link_to image_tag('work/discovery.jpg'), work_discovery_path, class: "border" %>
				<h3><%= link_to "Discovery", work_discovery_path %></h3>
			</div>
		</div>
	</div>
</div>