config/routes.rb
Lauralee::Application.routes.draw do

  # Home Page
  root to: "welcome#index"

  # Main Nav / Works
  get 'work/majorfinder' => 'work#majorfinder'
  get 'work/discovery' => 'work#discovery'
  get 'work/bloccit' => 'work#bloccit', path: "work/training-community"
  get 'work/wikiland' => 'work#wikiland'

  # Main Nav / About
  get "/about" => 'welcome#about'
  get "/test" => 'welcome#test'
  get "/varsitytutors" => 'welcome#varsitytutors'
  get "/confirmed" => 'welcome#confirm_subscription'

  # Playground
  get "/playground/*page" => "playground#show"
  get "/playground" => "playground#show", page: "index"

  # Main Nav / Feedback
  resources :feedbacks

  # Main Nav / Lessons
  get '/git', to: redirect('/courses')
  get '/git/lessons', to: redirect('/courses')
  resources :courses do
    resources :lessons, path: "lesson"
  end
  get '/git' => 'courses#git'


  # Devise
  devise_for :users
  resources :users, only: [:update]

  # Resources -> remove soon
  scope '/resources' do
    get '/freeimages' => 'welcome#freeimages'
    get "/about_me" => 'welcome#about_me', path: "a-little-about-me"
  end
  get "/resources" => 'welcome#resources'

  # Blog
  get 'blog/tags' => 'tags#index', as: :tags
  get 'blog/tags/:tag' => 'tags#show', as: :tag
  resources :posts, path: "blog"



end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	belongs_to :user

	# Validations
	validates :most_interested, length: { minimum: 5 }, presence: true
	validates :user, presence: true
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all.order("created_at DESC")
    @users = User.all.order("created_at DESC")
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = current_user.feedbacks.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: 'Thank you so much for your input!' }
        format.json { render action: 'show', status: :created, location: @feedback }
      else
        format.html { render action: 'new' }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Your feedback was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:most_interested, :user_id)
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<div id="form">
  <%= form_for(@feedback) do |f| %>
    <div class="row">
      <div class="small-12 columns">
        <% if @feedback.errors.any? %>
          <div id="error_explanation">
            <p class="error"><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</p>
            <ul>
              <% @feedback.errors.full_messages.each do |msg| %>
                <li><p><%= msg %></p></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="small-12 columns">
        <%= f.text_area :most_interested %>
      </div>
    </div>
    

    <div class="row">
      
      <div class="small-12 medium-7 medium-centered columns">
        <%= f.submit "Submit", class: "button expand" %>
      </div>
      
    </div>
    

  <% end %>

</div>

app/views/feedbacks/edit.html.erb
<div id="thoughtful-feedback">
	<div class="row">
		<h1 class="text-center">Edit My Feedback</h1>
	</div>

	<%= render 'form' %>

	<div class="row text-center">
		<p><%= link_to 'Cancel', @feedback, class: "white" %> </p>
	</div>
</div>

app/views/feedbacks/index.html.erb
<% if current_user.role == "admin" %>
  <div class="row medium-spacer-top small-spacer-bottom">
    <h2>Hey Commander!</h2>
    <% @feedbacks.each do |f| %>
      <!-- View all feedback - only for me -->
        <div class="panel">
          <%= simple_format(f.most_interested) %>
          <p class="created-by">Submitted <%= time_ago_in_words(f.created_at) %> ago by <%= f.user.email %>.</p>
          <%= link_to 'View', f, class: "pink-link-left space-right" %> | <%= link_to 'Edit', edit_feedback_path(f), class: "pink-link-left space-left space-right" %> | <%= link_to 'Destroy', f, method: :delete, data: { confirm: 'Are you sure? You will remove this feedback from the database and can\'t get it back.' }, class: "pink-link-left space-left" %>
        </div>
    <% end %>
  </div>
  <hr>
<% end %>


<% if current_user.feedbacks.count > 0 %>
  <div class="row">
    <div class="big-spacer-top small-spacer-bottom">
      <h1 class="text-center">Thank you for your feedback!</h1>
    </div>
  </div>
    
  <div class="row">
    <% current_user.feedbacks.each do |f| %>
      <div class="small-spacer">
        <div class="panel">
          <%= simple_format(f.most_interested) %>
          <p class="created-by">Submitted <%= time_ago_in_words(f.created_at) %> ago by <%= f.user.email %>.</p>
          <%= link_to 'Edit Feedback', edit_feedback_path(f), class: "pink-link-left space-right" %> | <%= link_to 'View Feedback', feedback_path(f), class: "pink-link-left space-left" %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="row medium-spacer-top">
    <h2>You Don't Have Any Feedback</h2>
    <p class="text-center">I would sincerely love to hear your input and suggestions. Sincerely.</p>
  </div>
<% end %>

<div class="small-spacer-bottom">
  <div class="row">
    <div class="small-12 medium-6 medium-centered columns">
      <% if current_user.feedbacks.count > 0 %>
        <%= link_to 'Share Another Idea', new_feedback_path, class: "button expand" %>
      <% else %>
        <div class="small-spacer">
          <%= link_to "Share An Idea", new_feedback_path, class: "button expand" %>
        </div>
      <% end %>
    </div>
  </div>
</div>


<% if current_user.role == "admin" %>
  <div class="row medium-spacer-top small-spacer-bottom">
    <h2>Hey Lauralee!</h2>
    <p><%= @users.count %> people signed up so far.</p>
    <% @users.each do |u| %>
      <!-- View all feedback - only for me -->
        <div class="panel">

          <p><%= u.name %></p>
          <p><%= u.email %></p>
          <p class="created-by">Signed up <%= time_ago_in_words(u.created_at) %> and has shared <%= u.feedbacks.count %> ideas. </p>
          
        </div>
    <% end %>
  </div>
  <hr>
<% end %>

app/views/feedbacks/new.html.erb
<div id="thoughtful-feedback">
	<div class="row">
		<div class="small-12 columns">
			<h2>I Would Love Your Feedback!</h2>
			<p>I'm working hard creating resources and training that <em>I think</em> you'll love. But, I'm honestly not sure if I'm focusing on what you <em>most want to learn</em>.</p>
			<p>If I were to create a course or a valuable resource <em>just for you</em>, what would it be? What do you want to learn from me?</p>
		</div>
	</div>
	

	<%= render 'form' %>

	<div class="row text-center">
		<p><%= link_to 'View Your Feedback', feedbacks_path, class: "white" %></p>
	</div>

	
</div>

app/views/feedbacks/show.html.erb
<div id="thoughtful-feedback">
	<div class="row">
		<div class="small-12 columns">
			<h1 class="text-center">Your Feedback</h1>
		</div>
		<div class="small-12 medium-8 medium-centered columns">
			<div class="big-spacer-top">
				<p><%= simple_format(@feedback.most_interested) %></p>
				<p class="created-by">submitted <%= time_ago_in_words(@feedback.created_at) %> ago by <%= @feedback.user.email %></p>
			</div>
		</div>
		<div class="small-12 medium-6 medium-centered columns small-spacer-top">
			<%= link_to 'Edit', edit_feedback_path(@feedback), class: "button expand" %>
		</div>
	</div>
	<div class="row text-center">
		<div class="small-spacer-top">
			<p><%= link_to 'View All Your Feedback', feedbacks_path, class: "pink-link-center" %> </p>
		</div>
	</div>
</div>