config/routes.rb
Lauralee::Application.routes.draw do

  # Home Page
  root to: "welcome#index"

  # Main Nav / Works
  get 'work/majorfinder' => 'work#majorfinder'
  get 'work/discovery' => 'work#discovery'
  get 'work/bloccit' => 'work#bloccit', path: "work/training-community"
  get 'work/wikiland' => 'work#wikiland'

  # Main Nav / About
  get "/about" => 'welcome#about'
  get "/test" => 'welcome#test'
  get "/varsitytutors" => 'welcome#varsitytutors'
  get "/confirmed" => 'welcome#confirm_subscription'

  # Playground
  get "/playground/*page" => "playground#show"
  get "/playground" => "playground#show", page: "index"

  # Main Nav / Feedback
  resources :feedbacks

  # Main Nav / Lessons
  get '/git', to: redirect('/courses')
  get '/git/lessons', to: redirect('/courses')
  resources :courses do
    resources :lessons, path: "lesson"
  end
  get '/git' => 'courses#git'


  # Devise
  devise_for :users
  resources :users, only: [:update]

  # Resources -> remove soon
  scope '/resources' do
    get '/freeimages' => 'welcome#freeimages'
    get "/about_me" => 'welcome#about_me', path: "a-little-about-me"
  end
  get "/resources" => 'welcome#resources'

  # Blog
  get 'blog/tags' => 'tags#index', as: :tags
  get 'blog/tags/:tag' => 'tags#show', as: :tag
  resources :posts, path: "blog"



end

app/views/layouts/_flash.html.erb
<!-- Flash Messages -->
<% if flash[:notice] %>
	<div class="nav-notification text-center">
		<div data-alert class="alert-box success">
			<%= flash[:notice] %>
			<%= link_to "&times;".html_safe, "#", class: "close" %>
		</div>
	</div>
<% elsif flash[:error] %>
	<div class="nav-notification text-center">
		<div data-alert class="alert-box alert">
			<%= flash[:error] %>
			<%= link_to "&times;".html_safe, "#", class: "close" %>
		</div>
	</div>
<% elsif flash[:alert] %>
	<div class="nav-notification text-center">
		<div data-alert class="alert-box">
			<%= flash[:alert] %>
			<%= link_to "&times;".html_safe, "#", class: "close" %>
		</div>
	</div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <footer>
    <div class="row text-center">
      <div class="small-6 small-centered columns">
        <p>Made with <span>♥</span> in Tucson, AZ</p>
      </div>
    </div>
  </footer>
</div>

app/views/layouts/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43450042-1', 'lauraleeflores.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<div id="header">
	<div class="row">
		<div class="small-12 small-centered medium-6 medium-uncentered columns">
			<%= link_to "Lauralee Flores", root_path, class: "logo" %>
		</div>
		<div class="show-for-medium-up medium-6 columns text-right">
			<div class="mini-spacer-top">
				<% if user_signed_in? %>
					<%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "button-small" %>
				<% else %>
					<%= link_to "Sign In", "#", "data-reveal-id" => "sign-in-modal", class: "ghost-button" %>
				<% end %>
			</div>
		</div>
	</div>

	<!-- Intro Text -->
	<div class="header-call">
		<div class="row">
			<div class="small-12 medium-11 medium-centered columns text-center">
				<h1>Creating Ruby on Rails Applications that are <em>Minimal</em>, <em>Usable</em>, and <em>Persuasive</em>.</h1>
			</div>
		</div>
	</div>
		

	<% if user_signed_in? %>
		<div class="row">
			<div class="small-12 medium-8 medium-centered columns">
				<div class="small-spacer-top">
					<div class="big-spacer">
						<%= link_to "Thank You For Signing Up", resources_path, class: "button expand button-pink" %>
					</div>
				</div>
			</div>
		</div>
	<% else %>
		<div id="form">
			<div class="row">
				<div class="small-12 medium-8 medium-centered columns">
					<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
						<%= devise_error_messages! %>

						<%= f.text_field :name, autofocus: true, placeholder: "First Name" %>

						<%= f.email_field :email, placeholder: "Email" %>

						<%= f.password_field :password, autocomplete: "off", placeholder: "Password" %>

						<%= f.submit "Send Me Training When It's Available", class: "button expand sign-up" %>
					<% end %>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/layouts/_nav.html.erb
<% unless current_page?(root_path) %>
	<div id="nav">
		<div class="fixed">
			<div class="contain-to-grid">
				<nav class="top-bar" data-topbar>
					<ul class="title-area">
						<li class="name">
							<h1><%= link_to "Lauralee Flores", root_path %></h1>
						</li>
						<li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
					</ul>

					<section class="top-bar-section">
						<!-- Right Nav Section -->
						<ul class="right">
							<li class="<%= 'active' if current_page?(root_path) %><%= 'active' if controller.controller_name == 'work' %>"><%= link_to "Home", root_path %></li>
							<li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>
							<!-- <li class="<%# 'active' if current_page?(resources_path) %><%= 'active' if current_page?(freeimages_path) %><%= 'active' if current_page?(about_me_path) %>"><%= link_to "Resources", resources_path %></li> -->
							<li class="<%= 'active' if controller.controller_name == 'posts' %><%= 'active' if controller.controller_name == 'tags' %>"><%= link_to "Blog", posts_path %></li>
							<!-- <li class="<%= 'active' if controller.controller_name == 'feedbacks' %>"><%= link_to "Feedback", new_feedback_path %></li> -->
							<li class="has-dropdown <%= 'active' if current_page?(edit_user_registration_path) %>">
								<% if current_user %>
									<%= link_to "#{ current_user.name.present? ? current_user.name : current_user.email}", "#" %>
										<ul class="dropdown">
											<li><%= link_to "My Account", edit_user_registration_path %></li>
											<li><%= link_to "Feedback", feedbacks_path %></li>
											<li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
										</ul>
								<% else %>
									<!-- <li class="<%= 'active' if current_page?(new_user_registration_path) %>"><%= link_to "Sign Up", new_user_registration_path %></li> -->
								<% end %>
							</li>
						</ul>
					</section>
				</nav>
			</div>
		</div>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Lauralee Flores | Design + Code" %></title>
    <meta name="og:description" content="<%= content_for?(:description) ? yield(:description) : "Making beautiful websites users love." %>">
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <!-- start Facebook share info -->
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= content_for?(:domain) ? yield(:domain) : "http://www.lauraleeflores.com#{url_for}" %>" />
    <meta property="og:title" content="<%= content_for?(:title) ? yield(:title) : "Lauralee Flores | Design + Code" %>" />
    <meta property="og:image" content="<%= content_for?(:image) ? yield(:image) : "https://s3.amazonaws.com/lauraleeflores/lauraleeflores_com.jpg" %>" />
    <!-- <meta property="fb:app_id" content="318624068512773" /> -->
    <!-- End Facebook share info -->
  </head>

  <body>
    <%= render partial: 'layouts/nav' %>
    <%= render partial: 'layouts/flash' %>

    <%= yield %>

    <% unless current_page?(root_path) %>
      <%= render partial: 'layouts/footer' %>
    <% end %>

    <!-- Modals for signing up or signing in -->
    <%= render partial: 'welcome/sign_up' %>
    <%= render partial: 'welcome/sign_in' %>

    <div class="container">
      <%= debug(params) if Rails.env.development? %>
    </div>

    <%= javascript_include_tag "application" %>
    <% if Rails.env.production? %>
      <%= render 'layouts/ga' %>
    <% end %>

  </body>
</html>